# sample Prometheus config
# this assumes that your Prometheus instance can access this application on localhost:8080

global:
  scrape_interval: 15s # set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout: 1ms # the global default is 10s.

scrape_configs:
  - job_name: 'spring boot scrape'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['spring-mongodb:8080'] # docker container name, can also use docker.host.internal:8080